# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ListService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ListService.proto\x12\x0clist_service\"\x0e\n\x0c\x45mptyMessage\"\x15\n\x04List\x12\r\n\x05items\x18\x01 \x03(\x05\"\x18\n\x08ListItem\x12\x0c\n\x04item\x18\x01 \x01(\x05\"$\n\x10ListItemPosition\x12\x10\n\x08position\x18\x01 \x01(\x05\"0\n\x0eListItemInsert\x12\x0c\n\x04item\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\"\x1b\n\x08ListSort\x12\x0f\n\x07reverse\x18\x01 \x01(\x08\x32\xf0\x02\n\x0bListService\x12;\n\x07GetList\x12\x1a.list_service.EmptyMessage\x1a\x12.list_service.List\"\x00\x12\x36\n\x06\x41ppend\x12\x16.list_service.ListItem\x1a\x12.list_service.List\"\x00\x12<\n\x06Insert\x12\x1c.list_service.ListItemInsert\x1a\x12.list_service.List\"\x00\x12\x36\n\x06\x44\x65lete\x12\x16.list_service.ListItem\x1a\x12.list_service.List\"\x00\x12@\n\x04\x46ind\x12\x16.list_service.ListItem\x1a\x1e.list_service.ListItemPosition\"\x00\x12\x34\n\x04Sort\x12\x16.list_service.ListSort\x1a\x12.list_service.List\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ListService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _EMPTYMESSAGE._serialized_start=35
  _EMPTYMESSAGE._serialized_end=49
  _LIST._serialized_start=51
  _LIST._serialized_end=72
  _LISTITEM._serialized_start=74
  _LISTITEM._serialized_end=98
  _LISTITEMPOSITION._serialized_start=100
  _LISTITEMPOSITION._serialized_end=136
  _LISTITEMINSERT._serialized_start=138
  _LISTITEMINSERT._serialized_end=186
  _LISTSORT._serialized_start=188
  _LISTSORT._serialized_end=215
  _LISTSERVICE._serialized_start=218
  _LISTSERVICE._serialized_end=586
# @@protoc_insertion_point(module_scope)
